# Generated by Django 5.1.6 on 2025-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_order_quantity_alter_order_total_price_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product_images/default.jpg", upload_to="product_images/"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
