# Generated by Django 5.1.6 on 2025-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_product_image_url_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
